const ALERT = 'ALERT';
const REFETCH_CHATS = 'REFETCH_CHATS';


const SEND_ATTACHMENT = 'SEND_ATTACHMENT';
const SEND_CHAT = 'SEND_CHAT';

const SEND_REQUEST = 'SEND_REQUEST';

// Socket events

const NEW_MESSAGE = 'NEW_MESSAGE';

const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT';

export{ALERT, REFETCH_CHATS, SEND_ATTACHMENT,SEND_CHAT,SEND_REQUEST,NEW_MESSAGE,NEW_MESSAGE_ALERT}